[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18" } # Match your local Node.js version

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"